config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  get 'welcome/index'

  get 'about' => 'welcome#about'
	get 'contact' => 'welcome#contact'
	
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
      @destinations = Destination.all 
    else
      @destinations = Destination.where(country: params[:country].titleize)
    end
    @my_countries = Destination.select(:country).order(:country).distinct
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar, :latitude, :longitude, :adddress)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@homeland = 'Puerto Rico'
  	@countries = ['Italy','Bulgaria','Croatia','India']
  	@picsofchile =['atacama.jpg','atacama2.jpg','atacama3.jpg','atacama4.png']
  end

  def about
  	@color = params[:color]
  end
  
  def contact
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(destination) do |f| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 	
 	<div class="field form-group">
    <%= f.label :address %><br>
    <%= f.text_field :adddress, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>
   <div class="field form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div> 
  <div class="field form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |c| %>
    <li><%= link_to "#{c.country}", destinations_path(country: c.country)%></li>
  <% end %>
</ul>


<h1>My Destination Wish List</h1>
<div class="row">
	<% @destinations.each do |destination| %>
    <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
        
      	 <h2><%= destination.city %></h2>
				 <h3><%= destination.country %></h3>
				 <h4>Population: <%= destination.population %></h4>
				 <% if destination.avatar_file_name != nil %>
				   <%= image_tag destination.avatar.url(:medium), class: "img-responsive" %>
				 <% end %>
				 <p><%= destination.description %></p>
				 
         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   address = '<%= j @destination.adddress %>';
   description = '<%= j @destination.description %>';
<% end %>

<h1><%= @destination.city %>, <%= @destination.country %></h1>
<h2>Population <%= @destination.population %></h2>
<%= image_tag @destination.avatar.url %>
<p> <%= @destination.description %></p>

<div id="destination-map"></div>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %> 
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>TravelApp</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <%= csrf_meta_tags %>
		<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  </head>

  <body>
  	<%= javascript_include_tag"https://maps.googleapis.com/maps/api/js?key=AIzaSyBpECpbA1LHDjUsJjDCrxDjq9c-9pRdikM" %>
  	<nav class="navbar navbar-default">
  		<div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
    			<div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      		  <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
    		    <span class="icon-bar"></span>
        		<span class="icon-bar"></span>
	      		</button>
  	    		<%= link_to "Travel", root_path, class: "navbar-brand" %>
  	    		<ul class="nav navbar-nav">
  						<li class="active">
    					<%= link_to 'About', about_path %>
  						</li>
  						<li>
     					<%= link_to 'Destinations', destinations_path %>
  						</li>
  					</ul>
    			</div>
			    <!-- Collect the nav links, forms, and other content for toggling -->
    			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
      		  	<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
			        <li><a href="#">Link</a></li>
  	  		    <li class="dropdown">
    	    	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          		<ul class="dropdown-menu">
      	      	<li><a href="#">Action</a></li>
	        	    <li><a href="#">Another action</a></li>
  	        	  <li><a href="#">Something else here</a></li>
    	        	<li role="separator" class="divider"></li>
	    	        <li><a href="#">Separated link</a></li>
  	    	      <li role="separator" class="divider"></li>
    	    	    <li><a href="#">One more separated link</a></li>
      	    	</ul>
	        		</li>
			      </ul>
      			<form class="navbar-form navbar-left">
			        <div class="form-group">
      			    <input type="text" class="form-control" placeholder="Search">
			        </div>
      			  <button type="submit" class="btn btn-default">Submit</button>
			      </form>
      			<ul class="nav navbar-nav navbar-right">
			        <li><%= link_to "About", about_path %></li>
      			  <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
    		      <ul class="dropdown-menu">
			          <li><a href="#">Action</a></li>
      		      <li><a href="#">Another action</a></li>
          		  <li><a href="#">Something else here</a></li>
		            <li role="separator" class="divider"></li>
    		        <li><a href="#">Separated link</a></li>
        		  </ul>
			       </li>
      		</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
  	<div class='container'>
    	<%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<style>
	body{
		background: <%= @color %>;
	}
</style>
<h1>About me</h1>
<p>Lots of interesting stuffs.</p>
<p>My favorite color is <%= @color %>

app/views/welcome/contact.html.erb
<h1>This is the contacts page</h1>
<p> This is the contacts page</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my very awesome travel site.</p>

<%= @homeland %>
<ul>
	<% @countries.each do |country| %>
		<li><%= country %></li>
	<% end %>
</ul>

<% @picsofchile.each do |picture| %>
		<%= image_tag picture, class: "img-responsive", alt: "Atacama",
                          id: "chile",
                          class: "country",
                          height: 300,
                          width: 400 %>
<% end %>

<div id="map-canvas"></div>